### ISSUE TITLE
"ButtonElevation" twice in Uno.Themes.Win.Markup

### ISSUE THREAD

**Issue by carldebilly** [unoplatform/Uno.Themes#1264]
## The problem
The resource "ButtonElevation" is defined twice in https://github.com/unoplatform/Uno.Themes/blob/master/src/library/Uno.Themes.WinUI.Markup/Theme/Button.cs, causing a crash in Xaml2CSharp.

## Error message
```
dotnet.native.js:1629 System.ArgumentException: An item with the same key has already been added. Key: ButtonElevation
put_char @ dotnet.native.js:1629
dotnet.native.js:1629    at System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Uno.Extensions.XamlToCsharp.Xaml2Csharp.Resolvers.IPropertyInfo, Uno.Extensions.XamlToCsharp, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null]].TryInsert(String key, IPropertyInfo value, InsertionBehavior behavior)
put_char @ dotnet.native.js:1629
dotnet.native.js:1629    at System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Uno.Extensions.XamlToCsharp.Xaml2Csharp.Resolvers.IPropertyInfo, Uno.Extensions.XamlToCsharp, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null]].Add(String key, IPropertyInfo value)
put_char @ dotnet.native.js:1629
dotnet.native.js:1629    at System.Linq.Enumerable.ToDictionary[ValueTuple`2,String,IPropertyInfo](ValueTuple`2[] source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
put_char @ dotnet.native.js:1629
dotnet.native.js:1629    at System.Linq.Enumerable.ToDictionary[ValueTuple`2,String,IPropertyInfo](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
put_char @ dotnet.native.js:1629
dotnet.native.js:1629    at Uno.Extensions.XamlToCsharp.Xaml2Csharp.Xaml2CSharpConverter.Process(Xaml2CSharpConvertSettings settings, XElement& xaml, TextWriter& output)
put_char @ dotnet.native.js:1629
dotnet.native.js:1629    at Uno.Extensions.XamlToCsharp.Xaml2Csharp.Xaml2CSharpConverter.Uno.Extensions.XamlToCsharp.Xaml2Csharp.IXaml2CSharpConverter.Process(Xaml2CSharpConvertSettings settings, XElement& xaml, TextWriter& output)
```

## Source
Present in both `Theme.Button.Resources.Elevated.Elevation.Default` and `Theme.Button.Resources.Filled.Elevation`.

## How to fix it
Please remove one of them to fix the bug.

**Comment by kazo0** [comment]
```csharp
[ResourceKeyDefinition(typeof(double), "ButtonElevation")]
public static ThemeResourceKey<double> Elevation => new("ButtonElevation");
```

Is defined once the Filled class and once in the FilledTonal class since both styles use that resource in their templates. 

There's no shared class of `Theme.Button,Resources` that all style variants use, shouldn't we just ignore them if the key is already added?

**Comment by Xiaoy312** [comment]
I believe this is not an issue from themes sides, but xaml2cs. 
I am not sure whether the problem is?:
a. `Elevation` exist under two branches: Theme.Button.Resources.(Elevated or Filled).Elevation; OR
b. `Elevation` arent the same from the two branches: one being a "resource-definition", and another being a class containing multiple of "resource-definitions"

@carldebilly could you also include the related xaml that created this error?
